ExaminationSystemITI/ExaminationSystemITI/Models/Tables/Choice.cs
using ExaminationSystemITI.Abstractions.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystemITI.Models.Tables
{
    public class Choice
    {
        [StringLength(450,ErrorMessage ="Invalid Text Length",MinimumLength =2)]
        [Required]
        public string Text { get; set; }
        [Range(1,50,ErrorMessage ="Invalid Question ID!")]
        [Required]
        public int Id { get; set; }

        [ForeignKey("Id")]
        public Question Question { get; set; }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Models/ViewModels/ChoiceViewModel.cs
using ExaminationSystemITI.Models.Tables;

namespace ExaminationSystemITI.Models.ViewModels
{
    public class ChoiceViewModel
    {
        public Choice Choice { get; set; } = new Choice();
        public string NewText { get; set; }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Controllers/ChoiceController.cs
using ExaminationSystemITI.Abstractions.Interfaces;
using ExaminationSystemITI.Models.Tables;
using ExaminationSystemITI.Models.ViewModels;
using ExaminationSystemITI.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace ExaminationSystemITI.Controllers
{
    public class ChoiceController : Controller
    {
        IChoiceService _choice;
        public ChoiceController(IChoiceService choice)
        {
            _choice = choice;
        }
        public IActionResult Read()
        {
            var choices = _choice.GetAll();
            return View(choices);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Choice choice)
        {
            _choice.Add(choice);
            return RedirectToAction("Read");
        }

        [HttpGet]
        public IActionResult Edit(int id, string text)
        {
            return View(new Choice() { Id = id, Text = text });
        }

        [HttpPost]
        public IActionResult Edit(Choice choice, string newText)
        {
            _choice.Update(choice, newText);
            return RedirectToAction("Read");
        }
        public IActionResult Delete(int id, string text)
        {
            _choice.Delete(new Choice() { Id = id, Text = text });
            return RedirectToAction("Read");
        }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Views/Choice/Create.cshtml
@using ExaminationSystemITI.Models.Tables
@model Choice;

@{
    ViewData["Title"] = "Create";
    Layout = "_DashboardLayout";
}

<h1 class="poppins-bold" style="color: var(--custom-black)">Create Choice</h1>
<hr style="backround-color: var(--custom-black); color: var(--custom-black); height: 1px;" />
<div class="row w-100">
    <div class="col-md-4 w-100">
        <form method="post" class="d-flex flex-column" style="gap: 16px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>

            <div class="form-group w-100 d-flex flex-column" style="margin-top: 8px; gap: 8px;">
                <input type="submit" value="Create" class="poppins-semibold w-100 rounded" style="border: none; background-color: var(--custom-red); color: var(--custom-white); padding: 8px 16px;" />
                <a asp-action="read" asp-controller="choice" class="w-100 poppins-semibold rounded" style="background-color: var(--custom-white); color: var(--custom-red);padding: 8px 16px; border: solid 1px var(--custom-red); text-decoration: none; text-align: center;">
                    Go Back
                </a>
            </div>
        </form>
    </div>
</div>

ExaminationSystemITI/ExaminationSystemITI/Views/Choice/Edit.cshtml
@using ExaminationSystemITI.Models.Tables
@model Choice

@{
    ViewData["Title"] = "Edit";
    Layout = "_DashboardLayout";
}

<h1 class="poppins-bold" style="color: var(--custom-black)">Edit Choice</h1>
<hr style="backround-color: var(--custom-black); color: var(--custom-black); height: 1px;" />
<div class="row w-100">
    <div class="col-md-4 w-100">
        <form method="post" class="d-flex flex-column" style="gap: 16px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Text" value="@Model.Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label poppins-semibold mb-1" style="color: var(--custom-black)">
                    New Text
                </label>
                <input name="newText" value="@Model.Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Id" value="@Model.Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="form-group w-100 d-flex flex-column" style="margin-top: 8px; gap: 8px;">
                <input type="submit" value="Edit" class="poppins-semibold w-100 rounded" style="border: none; background-color: var(--custom-red); color: var(--custom-white); padding: 8px 16px;" />
                <a asp-action="read" asp-controller="Choice" class="w-100 poppins-semibold rounded" style="background-color: var(--custom-white); color: var(--custom-red);padding: 8px 16px; border: solid 1px var(--custom-red); text-decoration: none; text-align: center;">
                    Go Back
                </a>
            </div>

        </form>

        @section Scripts {
            <partial src="_ValidationScriptsPartial"></partial>
        }

ExaminationSystemITI/ExaminationSystemITI/Views/Choice/Index.cshtml
@model List<Choice>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@* @foreach(var item in Model)
{
    
} *@

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Choice Text</th>
            <th>Question Id</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Text</td>
                <td>@item.Id</td>
                <td>
                    <a asp-controller="Choice" asp-action="Create" asp-route-id="@item.Id" class="btn btn-primary">Create</a>

                    <a asp-controller="Choice" asp-action="Update" asp-route-Text="@item.Text" asp-route-QuestionId="@item.Id" class="btn btn-primary">Update</a>

                    <a asp-controller="Choice" asp-action="Delete" asp-route-Text="@item.Text" asp-route-QuestionId="@item.Id" class="btn btn-primary">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ExaminationSystemITI/ExaminationSystemITI/Views/Choice/Read.cshtml
@using ExaminationSystemITI.Models.Tables
@model List<Choice>
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_DashboardLayout";
}

<seciton class="w-100 d-flex flex-column" style="gap: 16px;">
    <select id="navigate" class="form-select w-100">
        <option class="form-control" value="/admin/read">Admin</option>
        <option class="form-control" value="/choice/read" selected>Choice</option>
        <option class="form-control" value="/course/read">Course</option>
        <option class="form-control" value="/department/read">Department</option>
        <option class="form-control" value="/exam/read">Exam</option>
        <option class="form-control" value="/instructor/read">Instructor</option>
        <option class="form-control" value="/question/read">Question</option>
        <option class="form-control" value="/student/read">Student</option>
        <option class="form-control" value="/topic/read">Topic</option>
        <option class="form-control" value="/user/read">User</option>
    </select>
    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this Choice?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a id="deleteChoiceLink" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>

    <table class="get-data table table-border table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Text</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="9">No Choices Exist!</td>
                </tr>
            }
            else
            {
                foreach (var choice in Model)
                {
                    <tr>
                        <td>@choice.Id</td>
                        <td>@choice.Text</td>
                        <td style="white-space: nowrap;">
                            <a asp-action="Edit" asp-controller="Choice" asp-route-id="@choice.Id" asp-route-text="@choice.Text" class="btn btn-primary poppins-semibold rounded" style="padding: 8px 16px; border: none;transition-duration: 0.25s; text-decoration: none; text-align: center;">
                                Update
                            </a>
                            <a asp-action="Delete" asp-controller="Choice" asp-route-id="@choice.Id" asp-route-text="@choice.Text" class="btn btn-danger poppins-semibold rounded" style="padding: 8px 16px; border: none;text-decoration: none; text-align: center;" onclick="return confirm('Are you sure?')">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <script>
        // Function to handle deletion confirmation
        function confirmDelete(id,text) {
            document.getElementById('deleteChoiceLink').href = '/Choice/Delete?id=' + id + "&text=" + text;
            $('#deleteConfirmationModal').modal('show');
        }

        var selectElement = document.getElementById('navigate');

        selectElement.addEventListener('change', function () {
            var selectedValue = selectElement.value;

            if (selectedValue) {
                window.location.href = selectedValue;
            }
        });
    </script>
</seciton>

ExaminationSystemITI/ExaminationSystemITI/Views/Choice/Update.cshtml
@model Choice

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Choice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Text"></label>
                <input value="@Model.Text" disabled class="form-control" />
            </div>
            
            <div class="form-group">
                <label>New Text</label>
                <input name="newText" value="@Model.Text" class="form-control" />
                <span asp-validation-for="@Model.Text"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Id"></label>
                <input value="@Model.Id"  disabled class="form-control" />
            </div>


            <input type="submit" value="Update Choice" class="btn btn-primary" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <partial src="_ValidationScriptsPartial"></partial>
}