ExaminationSystemITI/ExaminationSystemITI/Controllers/QuestionController.cs
using ExaminationSystemITI.Database;
using ExaminationSystemITI.Models.Tables;
using ExaminationSystemITI.Abstractions.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using ExaminationSystemITI.Abstractions.Interfaces;
using ExaminationSystemITI.Models.ViewModels;
using System.Security.Claims;

namespace ExaminationSystemITI.Controllers
{
    public class QuestionController : Controller
    {
        private readonly ApplicationDbContext _context;
        IQuestionInterface _questionService;
        ICourseService _courseService;
        public QuestionController(ApplicationDbContext context,IQuestionInterface questionService,ICourseService courseService)
        {
            _context = context;
            _questionService = questionService;
            _courseService = courseService;
        }


        public IActionResult Read()
        {
            if (User.IsInRole(ERole.Instructor.ToString()))
            {
                string insEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                var model = new questioncourses();


                var questions = _context.Questions.FromSqlInterpolated($"SELECT\r\n    e.*\r\nFROM\r\n    QUESTIONS e\r\nJOIN\r\n    Courses c ON e.CourseID = c.ID\r\nJOIN\r\n    CourseInstructor ic ON c.ID = ic.CoursesID\r\nJOIN\r\n    Instructors i ON ic.InstructorsID = i.ID\r\nWHERE\r\n    i.Email = {insEmail};\r\n").ToList();
                var course = _context.Courses.FromSqlInterpolated($"SELECT C.* FROM COURSES C JOIN Courseinstructor I ON C.ID=I.CoursesId JOIN INSTRUCTORS INS ON INS.EMAIL ={insEmail}").ToList();
                model.Questions = questions;
                model.Courses = course;
                return View(model);
            }
            else
            {
                var questions = _questionService.GetQuestions();
                var model = new questioncourses();
                model.Questions = questions;
                return View(model);
            }
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            string insEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Instructor instructor = _context.Instructors.FromSqlInterpolated($"SELECT * FROM INSTRUCTORS WHERE EMAIL = {insEmail}").ToList()[0];
            ViewBag.insCourses = _context.Courses.FromSqlInterpolated($"SELECT * FROM COURSES JOIN COURSEINSTRUCTOR ON COURSES.ID = COURSEINSTRUCTOR.COURSESID WHERE COURSEINSTRUCTOR.INSTRUCTORSID = {instructor.ID}").ToList();
            ViewBag.Courses = _context.Courses.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Question question, string[] choices)
        {
            //if (ModelState.IsValid)
            //{
                
                _context.Questions.Add(question);
                _context.SaveChanges();

               
                var course =  _context.Courses.Find(question.CourseId);
                if (course != null)
                {
                    course.Questions.Add(question);
                    _context.SaveChanges();
                }

              
                if (question.Type == EQuestionType.MCQ && choices != null)
                {
                    foreach (var choiceText in choices)
                    {
                        var choice = new Choice { Text = choiceText, Id = question.Id };
                        _context.Choices.Add(choice);
                    }
                    _context.SaveChanges();
                }
            return RedirectToAction("Read");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var question=_questionService.FindQuestion(id);
            return View(question);
        }
        [HttpPost]
        public IActionResult Edit(Question question)
        {
            _questionService.Update(question);
            return RedirectToAction("Read");
        }
        public IActionResult Delete(int id)
        {
           _questionService.DeleteQuestion(id);   
            return RedirectToAction("Read");
        }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Controllers/ReportingController.cs
using ExaminationSystemITI.Database;
using ExaminationSystemITI.Models.Tables;
using ExaminationSystemITI.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystemITI.Controllers
{
    public class ReportingController : Controller
    {
        ApplicationDbContext _dbContext;
        public ReportingController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;   
        }
        [HttpGet]
        public IActionResult StudentsByDepartment()
        {

            var departments = _dbContext.Departments.ToList();
            var viewModel = new StudentsByDepartmentViewModel
            {
                Departments = departments
            };
            return View(viewModel);
        }

       

        [HttpPost]
        public IActionResult StudentsByDepartment(StudentsByDepartmentViewModel viewModel)
        {
            var students = _dbContext.Students.FromSqlRaw("EXECUTE dbo.GetAllStudentsByDepartmentId @DepartmentId", new SqlParameter("@DepartmentId", viewModel.DepartmentId)).ToList();
            viewModel.Students = students;
            return View(viewModel);
        }

        public IActionResult reports (){
           
            return View();
        }

    }
}








//[HttpPost]
//[Route("Reporting/StudentsByDepartment/{departmentId}")]
//public IActionResult StudentsByDepartment(int departmentId)
//{

//    var students = _dbContext.Students.FromSqlRaw("EXECUTE dbo.GetAllStudentsByDepartmentId @DepartmentId", new SqlParameter("@DepartmentId", departmentId)).ToList();

//    return View();
//}

ExaminationSystemITI/ExaminationSystemITI/Controllers/StudentController.cs
using ExaminationSystemITI.Abstractions.Enums;
using ExaminationSystemITI.Abstractions.Interfaces;
using ExaminationSystemITI.Database;
using ExaminationSystemITI.Models.Tables;
using Microsoft.AspNetCore.Authorization;
using ExaminationSystemITI.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;

namespace ExaminationSystemITI.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        IStudentService _student;
        IDepartmentService _department;
        ICourseService _course;
        IInstructorService _instructor;
        IExamService _exam;

        public StudentController(ApplicationDbContext context , IStudentService student, IDepartmentService department, ICourseService course, IInstructorService instructor, IExamService exam)
        {
            _context = context;
            _student = student;
            _department = department;
            _course = course;
            _instructor = instructor;
            _exam = exam;
        }

        public void GetData()
        {
            
        }
        
        public IActionResult Index()
        {

            if (User.IsInRole(ERole.Student.ToString()))
            {

                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;


                var students = _student.GetAll().Where(s => s.Email == userEmail).AsQueryable().Include(s => s.StudentCourses).ThenInclude(c => c.Course);

                

                ////string studentEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Email")?.Value;
                ////Debug.WriteLine("User Email: " + studentEmail);
                ////Debug.WriteLine("asasa");
                //////ViewBag.Email = studentEmail;

                
                return View(students.ToList());
            }
            else
            {
                // For other roles get all students
                var students = _student.GetAll().AsQueryable().Include(s => s.StudentCourses).ThenInclude(c=>c.Course);
                return View(students.ToList());
            }
        }

        public IActionResult Read()
        {
            var studentCourses = new List<StudentCoursesViewModel>();
            var students = _student.GetAll();

            foreach (var student in students)
                studentCourses.Add(
                    new StudentCoursesViewModel()
                    {
                        Student = student,
                        Courses = _student.GetStudentCourses(student.Id)
                    }
                );

            return View(studentCourses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new StudentDepartmentsViewModel();
            ViewBag.Departments = _department.GetDepartments();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(Student student)
        {
            _student.Add(student);

            return RedirectToAction("Read");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = new StudentDepartmentsViewModel();
            viewModel.Student = _student.GetById(id);
            ViewBag.Departments = _department.GetDepartments();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(StudentDepartmentsViewModel viewModel)
        {
            _student.Update(viewModel.Student);
            return RedirectToAction("Read");
        }

        public IActionResult Delete(int id)
        {
            _student.Delete(id);
            return RedirectToAction("Read");
        }

        public IActionResult Exams(int Id)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var students = _student.GetAll().Where(s => s.Email == userEmail).AsQueryable();
            ViewBag.StudentId = students.First().Id;
            ViewBag.StudentName = students.First().FirstName;
            var viewModel = _course.FindStudentActiveExams(Id);
            return View(viewModel);
        }

        public IActionResult Done(int Id)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var students = _student.GetAll().Where(s => s.Email == userEmail).AsQueryable();
            ViewBag.StudentId = students.First().Id;
            ViewBag.StudentName = students.First().FirstName;
            var viewModel = _course.FindStudentDoneExams(Id);
            return View(viewModel);
        }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Views/Shared/_DashboardLayout.cshtml
@using ExaminationSystemITI.Abstractions.Enums
@{
    string view = this.ViewContext.View.Path.Split("/")[2].ToLower();
    bool isAdmin = User.IsInRole(ERole.Admin.ToString());
    bool isInstructor = User.IsInRole(ERole.Instructor.ToString());
    bool isStudent = User.IsInRole(ERole.Student.ToString());
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExaminationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/global/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExaminationSystem.styles.css" asp-append-version="true" />
    <style>
        button:hover {
            opacity: 0.5;
        }

        li:hover {
            background-color: var(--custom-black);
            opacity: 0.5;
        }

        @@media (max-width: 500px) {
            .side-text {
                display: none;
            }

            .side-bar {
                width: 80px !important;
            }

            .avatar-name {
                width: 48px !important;
            }
        }
    </style>
</head>
<body style="height: 100vh; overflow-y: hidden">
    <header class="w-100 custom-wrapper d-flex justify-content-center align-items-center shadow" style="background-color: var(--custom-white); height: 120px;">
        <img src="~/assets/images/logos/logo.svg" class="w-100" style="max-width: 120px;" alt="ITI Logo" />
    </header>
    <section class="w-100 d-flex" style="height: calc(100vh - 120px);">
        <div class="side-bar d-flex flex-column align-items-center" style="width: 160px; background-color: var(--custom-blue); padding: 32px 16px; gap: 32px;">
            @if (isStudent)
            {
                <img src="~/assets/images/avatars/student.svg" class="avatar-name rounded-circle" />
            }
            else if (isInstructor)
            {
                <img src="~/assets/images/avatars/instructor.svg" class="avatar-name rounded-circle" />
            }
            else
            {
                <img src="~/assets/images/avatars/admin.svg" class="avatar-name rounded-circle" />
            }
            <hr class="w-100" style="height: 1px; background-color: var(--custom-white)" />
            <div class="d-flex flex-column align-items-center justify-content-between" style="height: 100%; min-height: fit-content; gap: 32px;">
                <ul class="w-100 d-flex flex-column list-group" style="gap: 16px;">
                    @if (isStudent)
                    {
                        <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px;cursor: pointer; transition-duration: 0.25s;">
                            <img src="~/assets/icons/active.svg" style="width: 24px; height: 24px;" alt="Active" />
                            <p class="poppins-medium side-text m-0" style="color: var(--custom-white);">
                                <a asp-action="Exams" asp-controller="Student" asp-route-id="@ViewBag.StudentId" style="text-decoration: none; color: var(--custom-white)">
                                    Active
                                </a>
                            </p>
                        </li>
                        <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px;cursor: pointer; transition-duration: 0.25s;">
                            <img src="~/assets/icons/done.svg" style="width: 24px; height: 24px;" alt="Active" />
                            <p class="poppins-medium side-text m-0" style="color: var(--custom-white);">
                                <a asp-action="Done" asp-controller="Student" asp-route-id="@ViewBag.StudentId" style="text-decoration: none; color: var(--custom-white)">
                                    Done
                                </a>
                            </p>
                        </li>
                    }
                    else
                    {
                        if (isAdmin)
                        {
                            <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px; cursor: pointer; transition-duration: 0.25s;">
                                <a asp-action="Read" asp-controller="Student" class="d-flex align-items-center" style="text-decoration: none; color: var(--custom-white); gap: 16px;">
                                    <img src="~/assets/icons/crud.svg" style="width: 24px; height: 24px;" alt="Crud" />
                                    <p class="poppins-medium side-text m-0">
                                        CRUD
                                    </p>
                                </a>
                            </li>
                        }else if(isInstructor){
                            <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px; cursor: pointer; transition-duration: 0.25s;">
                                <a asp-action="Read" asp-controller="Question" class="d-flex align-items-center" style="gap: 16px; text-decoration: none; color: var(--custom-white);">
                                    <img src="~/assets/icons/crud.svg" style="width: 24px; height: 24px;" alt="Crud" />
                                    <p class="poppins-medium side-text m-0">
                                        Questions
                                    </p>
                                </a>
                            </li>

                            <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px; cursor: pointer; transition-duration: 0.25s;">
                                <a asp-action="Read" asp-controller="Exam" class="d-flex align-items-center" style="gap: 16px;text-decoration: none; color: var(--custom-white);">
                                    <img src="~/assets/icons/active.svg" style="width: 24px; height: 24px;" alt="Crud" />
                                    <p class="poppins-medium side-text m-0">
                                        Exams
                                    </p>
                                </a>
                            </li>
                        }
                        

                    }
                   @if (isAdmin){
                    <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="gap: 16px; padding: 8px 12px;cursor: pointer; transition-duration: 0.25s;">
                         <a asp-action="Reports" asp-controller="Reporting" class="d-flex align-items-center" style="text-decoration: none; color: var(--custom-white); gap: 16px;">
                            <img src="~/assets/icons/reports.svg" style="width: 24px; height: 24px;" alt="Reports" />
                            <p class="poppins-medium side-text m-0" style="color: var(--custom-white);">
                                Reports
                            </p>
                        </a>
                    </li>
                   }
                   
                    <li class="w-100 bg-transparent list-group-item border-0 d-flex align-items-center rounded" style="padding: 8px 12px; cursor: pointer; transition-duration: 0.25s;">
                        <a asp-action="info" asp-controller="Account" class="d-flex align-items-center" style="text-decoration: none; color: var(--custom-white); gap: 16px;">
                            <img src="~/assets/icons/account.svg" style="width: 24px; height: 24px;" alt="Crud" />
                            <p class="poppins-medium side-text m-0">
                                Account
                            </p>
                        </a>
                    </li>
                </ul>
                <form asp-controller="Account" asp-action="LogOut" method="post">
                    <button type="submit" class="w-100 border-0 d-flex align-items-center justify-content-between rounded" style="gap: 16px; padding: 8px 12px; cursor: pointer; background-color: var(--custom-red); transition-duration: 0.25s;">
                        <img src="~/assets/icons/signout.svg" style="width: 24px; height: 24px;" alt="Sign Out" />
                        <p class="poppins-medium side-text m-0" style="color: var(--custom-white); font-size: 15.75px;">
                            Sign Out
                        </p>
                    </button>
                </form>
            </div>
        </div>
        <main role="main" style="padding: 32px; overflow-y: scroll;" class="w-100">
            @RenderBody()
        </main>
    </section>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExaminationSystemITI/ExaminationSystemITI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExaminationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/global/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExaminationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>