ExaminationSystemITI/ExaminationSystemITI/Models/Tables/Topic.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystemITI.Models.Tables
{
    public class Topic
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int CourseId { get; set; }
        [ForeignKey("CourseId")]
        public Course Course { get; set; }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Controllers/TopicController.cs
using ExaminationSystemITI.Abstractions.Interfaces;
using ExaminationSystemITI.Models.Tables;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystemITI.Controllers
{
    public class TopicController : Controller
    {
        ITopicService _topic;
        ICourseService _course;
        public TopicController(ITopicService topic,ICourseService courseService)
        {
            _topic = topic;
            _course = courseService;
        }
     
        public IActionResult Read()
        {
            ICollection<Topic> topics = _topic.GetTopics();
            return View(topics);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.courses=_course.GetCourses();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Topic topic)
        {
            _topic.InsertTopic(topic);
            return RedirectToAction("Read");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var topic = _topic.FindTopic(Id);
            return View(topic);
        }

        [HttpPost]
        public IActionResult Edit(Topic topic)
        {
            _topic.EditTopic(topic);
            return RedirectToAction("Read");
        }

    
        public IActionResult Delete(int id)
        {
            _topic.DeleteTopic(id);
            return RedirectToAction("Read");
        }
    }
}

ExaminationSystemITI/ExaminationSystemITI/Views/Topic/Create.cshtml
@using ExaminationSystemITI.Models.Tables
@model ExaminationSystemITI.Models.Tables.Topic


@{
    ViewData["Title"] = "Create";
    Layout = "_DashboardLayout";
    var courses = ViewBag.courses;
}



<h1 class="poppins-bold" style="color: var(--custom-black)">Create Topic</h1>
<hr style="backround-color: var(--custom-black); color: var(--custom-black); height: 1px;" />
<div class="row w-100">
    <div class="col-md-4 w-100">
        <form method="post" class="d-flex flex-column" style="gap: 16px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)">Course</label>
                <select asp-for="CourseId" class="form-control">
                    <option value="">Select Courses</option>
                    @foreach (var course in courses)
                    {
                        <option value="@course.Id">@course.Name</option>
                    }
                </select>
            </div>
            <div class="form-group w-100 d-flex flex-column" style="margin-top: 8px; gap: 8px;">
                <input type="submit" value="Create" class="poppins-semibold w-100 rounded" style="border: none; background-color: var(--custom-red); color: var(--custom-white); padding: 8px 16px;" />
                <a asp-action="read" asp-controller="Topic" class="w-100 poppins-semibold rounded" style="background-color: var(--custom-white); color: var(--custom-red);padding: 8px 16px; border: solid 1px var(--custom-red); text-decoration: none; text-align: center;">
                    Go Back
                </a>
            </div>
        </form>
    </div>
</div>

ExaminationSystemITI/ExaminationSystemITI/Views/Topic/Edit.cshtml
@using ExaminationSystemITI.Models.Tables
@model ExaminationSystemITI.Models.Tables.Topic

@{
    ViewData["Title"] = "Edit";
    Layout = "_DashboardLayout";
}



<h1 class="poppins-bold" style="color: var(--custom-black)">Edit Topic</h1>
<hr style="backround-color: var(--custom-black); color: var(--custom-black); height: 1px;" />
<div class="row w-100">
    <div class="col-md-4 w-100">
        <form method="post" class="d-flex flex-column" style="gap: 16px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="Name" value="@Model.Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group d-none">
                <label asp-for="CourseId" class="control-label poppins-semibold mb-1" style="color: var(--custom-black)"></label>
                <input asp-for="CourseId" value="@Model.CourseId" class="form-control" />
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>

            <div class="form-group w-100 d-flex flex-column" style="margin-top: 8px; gap: 8px;">
                <input type="submit" value="Edit" class="poppins-semibold w-100 rounded" style="border: none; background-color: var(--custom-red); color: var(--custom-white); padding: 8px 16px;" />
                <a asp-action="read" asp-controller="Topic" class="w-100 poppins-semibold rounded" style="background-color: var(--custom-white); color: var(--custom-red);padding: 8px 16px; border: solid 1px var(--custom-red); text-decoration: none; text-align: center;">
                    Go Back
                </a>
            </div>

        </form>

ExaminationSystemITI/ExaminationSystemITI/Views/Topic/Read.cshtml
@using ExaminationSystemITI.Models.Tables
@model List<Topic>
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_DashboardLayout";
}

<seciton class="w-100 d-flex flex-column" style="gap: 16px;">
    <select id="navigate" class="form-select w-100">
        <option class="form-control" value="/admin/read">Admin</option>
        <option class="form-control" value="/choice/read">Choice</option>
        <option class="form-control" value="/course/read">Course</option>
        <option class="form-control" value="/department/read">Department</option>
        <option class="form-control" value="/exam/read">Exam</option>
        <option class="form-control" value="/instructor/read">Instructor</option>
        <option class="form-control" value="/question/read">Question</option>
        <option class="form-control" value="/student/read">Student</option>
        <option class="form-control" value="/topic/read" selected>Topic</option>
        <option class="form-control" value="/user/read">User</option>
    </select>
    <a asp-action="create" asp-controller="Topic" class="btn btn-success poppins-semibold rounded" style="padding: 8px 16px; border: none;text-decoration: none; text-align: center;">
        Create
    </a>
    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this Topic?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a id="deleteTopicLink" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
    <table class="get-data table table-border table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Course</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="5">No Topics Exist!</td>
                </tr>
            }
            else
            {
                foreach (var topic in Model)
                {
                    <tr>
                        <td>@topic.Id</td>
                        <td>@topic.Name</td>
                        <td>@topic.Course.Name</td>
                        <td style="white-space: nowrap;">
                            <a asp-action="Edit" asp-controller="Topic" asp-route-id="@topic.Id" class="btn btn-primary poppins-semibold rounded" style="padding: 8px 16px; border: none;transition-duration: 0.25s; text-decoration: none; text-align: center;">
                                Update
                            </a>
                            <a href="#" onclick="confirmDelete('@topic.Id')" class="btn btn-danger poppins-semibold rounded" style="padding: 8px 16px; border: none; text-decoration: none; text-align: center;">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <script>
          function confirmDelete(id) {
            document.getElementById('deleteTopicLink').href = '/Topic/Delete/' + id;
            $('#deleteConfirmationModal').modal('show');
        }

        var selectElement = document.getElementById('navigate');

        selectElement.addEventListener('change', function () {
            var selectedValue = selectElement.value;

            if (selectedValue) {
                window.location.href = selectedValue;
            }
        });
    </script>

</seciton>